import Head from "next/head";
import * as React from "react";
import * as Chakra from "@chakra-ui/react";

import GITHUB_ICON from "../src/images/GitHub-Mark-120px-plus.png";
import ToptalIcon from "../src/images/toptal.svg";
import CodementorIcon from "../src/images/codementor.svg";
import ArcIcon from "../src/images/arc.svg";

const CARD_LIST = [
  {
    prefix: "An",
    iconEl: <Chakra.Image boxSize={8} src={GITHUB_ICON.src} />,
    postfix: "Open Sourcer",
    href: "https://github.com/tomchentw",
    desc: "",
  },
  {
    prefix: "A",
    iconEl: <ToptalIcon />,
    postfix: "member",
    href: "https://www.toptal.com/resume/tom-chen",
    desc: "",
  },
  {
    prefix: "A",
    iconEl: <CodementorIcon />,
    postfix: "",
    href: "https://www.codementor.io/@tomchentw",
    desc: "",
  },
  {
    prefix: "An",
    iconEl: <ArcIcon />,
    postfix: "member",
    href: "https://arc.dev/tomchentw",
    desc: "",
  },
];

function Card({ card: { prefix, iconEl, postfix, href, desc } }) {
  return (
    <Chakra.LinkBox
      as={Chakra.VStack}
      align="stretch"
      bgColor="white"
      p={4}
      rounded={["md", "xl"]}
    >
      <Chakra.HStack spacing={2} as={Chakra.Heading} size="xl">
        <span>{prefix}</span>
        {iconEl}
        <span>{postfix}</span>
      </Chakra.HStack>
      <Chakra.Text>
        <Chakra.LinkOverlay href={href} isExternal>
          {href}
        </Chakra.LinkOverlay>
      </Chakra.Text>
      <Chakra.Text color="gray.600">{desc}</Chakra.Text>
    </Chakra.LinkBox>
  );
}

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>@tomchentw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Chakra.Box bgColor="gray.300" minH="100vh">
        <Chakra.Container maxW="80ch">
          <Chakra.VStack as="article" spacing={4} pt={12} textAlign="center">
            <Chakra.Heading size="2xl">Tom Chen</Chakra.Heading>
            <Chakra.Text fontSize={["md", "lg"]}>
              Building awesome and making software development more accessible.
            </Chakra.Text>
          </Chakra.VStack>
          <Chakra.SimpleGrid my={6} columns={[1, 2]} gap={[4, 6]}>
            {CARD_LIST.map((card) => (
              <Card key={card.href} card={card} />
            ))}
          </Chakra.SimpleGrid>
          <Chakra.Text fontSize="sm" maxW="40ch" mx="auto">
            {`If you're unimpressed with my website it's because I'm too busy hanging out with my family, building awesome things, mentoring people JavaScript, and doing stuff for the community.`}
          </Chakra.Text>
        </Chakra.Container>
      </Chakra.Box>
    </React.Fragment>
  );
}
